config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :products, only: [:index]
      post '/api-keys', to: 'api_keys#create'
      delete '/api-keys', to: 'api_keys#destroy'
      get '/api-keys', to: 'api_keys#index'
      # put '/user_edit',to: 'api_keys#user_edit'
      put '/user_edit/:id',to: 'tests#user_edit'

    end
  end

  resources :payment_notifications
  resources :order2s
  get '/express', to: 'order2s#express'
  
  # get '/user_feedbacks/new', to: "user_feedbacks#new"
  # post '/user_feedbacks', to: "user_feedbacks#create"
  resources :user_feed_backs
  post '/rate' => 'rater#create', :as => 'rate'
  # get 'emails/unsubscribe'
  
 get '/orders', to: 'orders#index'
 post '/orders/submit', to: "orders#submit"


  resources :projects do
    resources :tasks
  end

  get 'checkout', to: "checkout#index"

  resources :cart_items
  resources :carts
  resources :posts
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    namespace :admin do
      # resources :cars
      resources :users
      resources :categories
      resources :products
      root to: "users#index"
      
    end
    resources :products

    match "users/unsubscribe/:unsubscribe_hash" => "emails#unsubscribe", as: "unsubscribe", via: :all



    get "subcategories" , to: "products#subcategories"

   resources :cars

  #  devise_for :users, path: '', path_names: {
  #   sign_in: 'login',
  #   sign_out: 'logout',
  #   registration: 'signup'
  # },
  # controllers: {
  #   sessions: 'sessions',
  #   registrations: 'registrations'
  # }


  devise_for :users, :controllers => {:sessions => 'sessions', registrations: 'registrations'}
  root 'home#index'
  post "address/new" , to: "checkout#create"
  post "place_order" , to: "checkout#place_order"
  get "checkout/place_order" , to: "checkout#place_order_new"
  post "cart_items/quantity_update" , to: "cart_items#quantity_update"

  # delete "address/destroy/:id" , to: "checkout#destroy"
  delete "address/destroy/:id" , to: "checkout#destroy", as: "address_destroy"
  # resources :addresses
  # scope module: 'admin', path: 'fu' do
  #   resources :users
  # end
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cart_items, dependent: :destroy

    has_many :order2s
    # has_one :order2


    def add_product_to_cart(product, item_quantity)
      cart_item = self.cart_items.find_by(product_id: product.id)
      if cart_item
        if !(item_quantity.blank?)
            cart_item.quantity = cart_item.quantity + item_quantity.to_i
         end
        # cart_item = cart_item.increment(:quantity)
      else
        cart_item = self.cart_items.build(product_id: product.id)
      end
      cart_item
    end

    def total_price
        total_price = 0;
         self.cart_items.each do |cart_item|
            total_price = total_price + cart_item.product.price * cart_item.quantity
        end
        total_price
    end
  
   
    def check_product_quantity(product)
        if  cart_item.quantity > product.quantity
             return false
        end
        return true
    end

    def paypal_url(return_url, notify_url)
        values = {
          :business => 'sb-bu83a14721126@business.example.com',
          :cmd => '_cart',
          :upload => 1,
          :return => return_url,
          :invoice => id,
          :notify_url => notify_url
        }
        cart_items.each_with_index do |item, index|
          values.merge!({
            "amount_#{index+1}" => item.product.price,
            "item_name_#{index+1}" => item.product.model,
            "item_number_#{index+1}" => item.id,
            "quantity_#{index+1}" => item.quantity
          })
        end
        values
      end




end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart1, only: %i[ show edit update destroy ]
  before_action :set_cart
  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)
    respond_to do |format|
      if @cart.save
        @cart_item = @cart.cart_items.build(product_id: params[:product_id])
        if @cart_item.save
          format.html { redirect_to cart_url(@cart), notice: "Item successfully added in cart." }
          format.json { render :show, status: :created, location: @cart }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @cart.errors, status: :unprocessable_entity }
        end
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end



# DELETE /carts/1 or /carts/1.json
def destroy 
  @cart.destroy if @cart.id == session[:cart_id]
  session[:cart_id] = nil

  respond_to do |format|
    format.html { redirect_to root_path, notice: "Cart was successfully destroyed." }
    format.json { head :no_content }
  end
end




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart1
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div id="<%= dom_id cart %>">
</div>

app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Show this cart", @cart %> |
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Carts</h1>

<div id="carts">
  <% @carts.each do |cart| %>
    <%= render cart %>
    <p>
      <%= link_to "Show this cart", cart %>
    </p>
  <% end %>
</div>

<%= link_to "New cart", new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render "form", cart: @cart %>

<br>

<div>
  <%= link_to "Back to carts", carts_path %>
</div>

app/views/carts/show.html.erb
<div class="row keep-shopping pv1 mt-4 ">
  <div class="col-md-6">
    <h2>Shopping Cart</h2>
  </div>
  <div class="col-md-6">
  <div class="pull-right">
  <%= link_to 'Keep Shopping', products_path, class: 'btn btn-info' %>
  </div>
  </div>
</div>

<br/>
<hr />
<% # star_images%>
<% #= render_stars(@cart) %>


<div class="section">


<div class="row">
        <div class="col-md-3">
        <p><strong>Item</strong></p>
        </div>
          <div class="col-md-9">
                    
                  <div class="columns align-items-center">
                          <div class="row">
                              <div class="content col-md-5">
                              <p><strong>Product Description</strong></p>
                              </div>
                              <div class="content col-md-2">
                              <p><strong>Price</strong></p>
                              </div>
                              <div class="content col-md-2">
                              <p><strong>Quantity</strong></p>
                              </div>

                              <div class="col-md-3 has-text-right">
                              <p><strong>Subtotal</strong></p>
                              </div>

                          </div>
                  </div>
          </div>
  </div>
<hr/ >



<% count = 0%>
  <%= render(@cart.cart_items, count: count) %>

  <div class="row">
    <div class="col-md-10">
      <%= button_to 'Empty Cart', @cart, method: :delete, form: {data: { turbo_confirm: "Are you sure? " }}, class: "btn btn-danger" %>
        <div class="column total has-text-right">
          <h4 class="  title is-4">
            <span class="f5 has-text-grey">Total:</span>
            <span class="total-price"> <%= number_to_currency(@cart.total_price) %></span>
          </h4>
        </div>
    </div>

    <div class="col-md-2">
    <%= link_to 'Move to Checkout', checkout_path,  class: "btn btn-warning" %>
    </div>

</div>