config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :products, only: [:index]
      post '/api-keys', to: 'api_keys#create'
      delete '/api-keys', to: 'api_keys#destroy'
      get '/api-keys', to: 'api_keys#index'
      # put '/user_edit',to: 'api_keys#user_edit'
      put '/user_edit/:id',to: 'tests#user_edit'

    end
  end

  resources :payment_notifications
  resources :order2s
  get '/express', to: 'order2s#express'
  
  # get '/user_feedbacks/new', to: "user_feedbacks#new"
  # post '/user_feedbacks', to: "user_feedbacks#create"
  resources :user_feed_backs
  post '/rate' => 'rater#create', :as => 'rate'
  # get 'emails/unsubscribe'
  
 get '/orders', to: 'orders#index'
 post '/orders/submit', to: "orders#submit"


  resources :projects do
    resources :tasks
  end

  get 'checkout', to: "checkout#index"

  resources :cart_items
  resources :carts
  resources :posts
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    namespace :admin do
      # resources :cars
      resources :users
      resources :categories
      resources :products
      root to: "users#index"
      
    end
    resources :products

    match "users/unsubscribe/:unsubscribe_hash" => "emails#unsubscribe", as: "unsubscribe", via: :all



    get "subcategories" , to: "products#subcategories"

   resources :cars

  #  devise_for :users, path: '', path_names: {
  #   sign_in: 'login',
  #   sign_out: 'logout',
  #   registration: 'signup'
  # },
  # controllers: {
  #   sessions: 'sessions',
  #   registrations: 'registrations'
  # }


  devise_for :users, :controllers => {:sessions => 'sessions', registrations: 'registrations'}
  root 'home#index'
  post "address/new" , to: "checkout#create"
  post "place_order" , to: "checkout#place_order"
  get "checkout/place_order" , to: "checkout#place_order_new"
  post "cart_items/quantity_update" , to: "cart_items#quantity_update"

  # delete "address/destroy/:id" , to: "checkout#destroy"
  delete "address/destroy/:id" , to: "checkout#destroy", as: "address_destroy"
  # resources :addresses
  # scope module: 'admin', path: 'fu' do
  #   resources :users
  # end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  
  validate :check_product_quantity
   
   private
   def check_product_quantity
     product_quantity = Product.find(self.product_id).quantity
    #  debugger
     if self.quantity > product_quantity
      errors.add(:quantity, "There is not enough quantity regarding this product")
    end
  # debugger
    if self.quantity <= 0
      errors.add(:quantity, "There sholud be one qunatity")
    end
   end

end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :set_cart_item, only: %i[ show edit update destroy ]
  before_action :set_cart, only: [:create, :quantity_update]

  # GET /cart_items or /cart_items.json
  def index
    @cart_items = CartItem.all
  end

  # GET /cart_items/1 or /cart_items/1.json
  def show
  end

  # GET /cart_items/new
  def new
    @cart_item = CartItem.new

  end

  # GET /cart_items/1/edit
  def edit
  end

  #do for showing error but now handle using there controller
  # def product_show
  #   @product = Product.find(params[:id])
  # end

  # POST /cart_items or /cart_items.json
  def create
     # we are getting @cart from the applicationcontroller
     quantity = 1
     @product = Product.find(params[:product_id])
     quantity = params[:product][:quantity] if params[:product][:quantity].present?
     @cart_item = @cart.add_product_to_cart( @product, quantity)
    #  debugger
    respond_to do |format|
      if @cart_item.save
        format.html { redirect_to cart_path(@cart_item.cart), notice: "Cart item was successfully created." }
        format.json { render :show, status: :created, location: @cart_item.cart }
      else
        format.html {render template: 'products/show', :id => @product.id, status: :unprocessable_entity}
        # format.html {render 'products/show', :id => @product.id, status: :unprocessable_entity}
        # format.html {render "products/show/#{@product.id}", status: :unprocessable_entity }
        # format.html { render :product_show, status: :unprocessable_entity }
        format.json { render json: @cart_item.errors, status: :unprocessable_entity }
      end
    end
  end



def quantity_update
  @product = Product.find(params[:product_id])
  @cart_item = @cart.cart_items.find_by(product_id: @product.id)

  @cart_item.quantity = params[:quantity]
  if @cart_item.quantity > 0
    if @cart_item.save
        sub_price = ActionController::Base.helpers.number_to_currency(@cart_item.product.price * @cart_item.quantity) 
        total_price = ActionController::Base.helpers.number_to_currency(@cart.total_price)
        data = {"quantity"=> @cart_item.quantity, "sub_price"=> sub_price, "total_price"=> total_price}
        render json: data
    else
        flash.now[:alert] = "#{@cart_item.errors.full_messages}"
        # test = render partial: "shared/message"
        render(partial: "shared/message")
        # render json: { partial: "shared/message", }
    end
  else
    flash.now[:alert] = "Qunatity cannot be zero"
    render partial: "shared/message"
  end

end






  # PATCH/PUT /cart_items/1 or /cart_items/1.json
  def update
    respond_to do |format|
      if @cart_item.update(cart_item_params)
        format.html { redirect_to cart_item_url(@cart_item), notice: "Cart item was successfully updated." }
        format.json { render :show, status: :ok, location: @cart_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cart_items/1 or /cart_items/1.json

 # DELETE /line_items/1 or /line_items/1.json
 def destroy
  @cart = Cart.find(session[:cart_id])

  @cart_item.destroy

  respond_to do |format|
    format.html { redirect_to cart_path(@cart), notice: "Cart item was successfully destroyed." }
    format.json { head :no_content }
  end
end


  # def destroy
  #   @cart_item.destroy

  #   respond_to do |format|
  #     format.html { redirect_to cart_items_url, notice: "Cart item was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart_item
      @cart_item = CartItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_item_params
      params.require(:cart_item).permit(:product_id, :cart_id, :quantity)
    end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/_cart_item.html.erb
<div class="row">

  <div class="col-md-3">
    <figure class="is-128x128 image">
    <%= image_tag(cart_item.product.image.url, size: "128x128")  %>

    </figure>
  </div>
  <div class="col-md-9">
  <strong><%= cart_item.product.title %></strong>
    <div class="columns align-items-center">
      <div class="row">
          <div class="content col-md-5">
            <%= cart_item.product.description %>
          </div>
          <div class="content col-md-2">
          <%= number_to_currency(cart_item.product.price) %>
          </div>
          <div class="content col-md-2">
              <%= form_with(model: cart_item) do |form| %>
                <div class="", id="<%= cart_item.product.id%>">
                    <%= form.number_field :quantity ,id: "cart_item_quantity_#{cart_item.product.id}", class: "cart_item_quantity", prev_val: "#{cart_item.quantity}" %>
                    <span id="<%= "error-#{cart_item.product.id}" %>"></spn>
                </div>
              <% end %>
          </div>

          <div class="col-md-3 has-text-right">
            <strong class="f4 sub-total", id="<%= "product-#{cart_item.product.id}" %>"><%= number_to_currency(cart_item.product.price * cart_item.quantity) %></strong>
            <div class="has-text-right">
            
              <%= button_to 'Remove Cart',cart_item, method: :delete, form: {data: { turbo_confirm: "Are you sure? " }}, class: "btn btn-danger mb-4" %>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>
<hr/ >

<style>
.cart_item_quantity {

  width:45px !important;
}
</style>

app/views/cart_items/_form.html.erb
<%= form_with(model: cart_item) do |form| %>
  <% if cart_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cart_item.errors.count, "error") %> prohibited this cart_item from being saved:</h2>

      <ul>
        <% cart_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.text_field :product_id %>
  </div>

  <div>
    <%= form.label :cart_id, style: "display: block" %>
    <%= form.text_field :cart_id %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cart_items/edit.html.erb
<h1>Editing cart item</h1>

<%= render "form", cart_item: @cart_item %>

<br>

<div>
  <%= link_to "Show this cart item", @cart_item %> |
  <%= link_to "Back to cart items", cart_items_path %>
</div>

app/views/cart_items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cart items</h1>

<div id="cart_items">
  <% @cart_items.each do |cart_item| %>
    <%= render cart_item %>
    <p>
      <%= link_to "Show this cart item", cart_item %>
    </p>
  <% end %>
</div>

<%= link_to "New cart item", new_cart_item_path %>

app/views/cart_items/new.html.erb
<h1>New cart item</h1>

<%= render "form", cart_item: @cart_item %>

<br>

<div>
  <%= link_to "Back to cart items", cart_items_path %>
</div>

app/views/cart_items/product_show.html.erb
<% content_for :body_class, 'bg-light' %>

<div class="section product-show mt-3 mb-5">
  <div class="row">
    <div class="col-md-8">
         <h2 class="title is-2"><%= @product.title %></h2>
           <div>
                <% if @product.brand? %>
                <span class="top inline-block pr-3"><%= @product.brand %></span>
                <% end %>

                <span class="top inline-block pr-3"><%= @product.model %></span>

                <% if @product.condition? %>
                <span class="top inline-block pr-3"><%= @product.condition %></span>
                <% end %>
            </div>
        <div class="feature-image rounded">
            <%= link_to image_tag(@product.image.url, size: "500x350" ) %>
        </div>

        <div class="content rounded mt-3 bg-white mb-5">
            <h3 class="subtitle is-4">Description</h3>
            <%= @product.description %>
            <h3 class="subtitle is-4 pt5">Product Specs</h3>
            <table class="table is-narrow mt-5">
                <% if @product.condition %>
                <tr>
                <td class="has-text-weight-bold">Condition:</td>
                <td><%= @product.condition %></td>
                </tr>
                <% end %>
                <% if @product.finish %>
                <tr>
                    <td class="has-text-weight-bold">Finish:</td>
                    <td><%= @product.finish %></td>
                </tr>
                <% end %>
                <% if @product.brand %>
                <tr>
                    <td class="has-text-weight-bold">Brand:</td>
                    <td><%= @product.brand %></td>
                </tr>
                <% end %>

                <tr>
                <td class="has-text-weight-bold">Model:</td>
                <td><%= @product.model %></td>
                </tr>
            </table>
        </div>
    </div>
    <div class="col-md-3 round  text-center">
        <div class="bg-white sideBox ">
            <h4 class="title is-5 has-text-centered"><%= number_to_currency(@product.price) %></h4>
            <p class="has-text-centered mb4">
            <% # @product.user.name %>
            </p>
            <%= form_with(model: Product.new ,url: cart_items_path(product_id: @product.id), class: "mb-2") do |form| %>
              <div class="test mb-4">
                 <%=  form.label :quantity %>
                  <%=  form.number_field :quantity %>
                  <p class='c-error'><%= show_errors(@cart_item, :quantity) %></p>
              </div>
              <%= form.submit 'Add to cart',  class: 'btn btn-info' %>
            <% end %>
            <% # button_to 'Add to cart', cart_items_path(product_id: @product.id), class: 'btn btn-info' %>
        </div>
    </div>
  </div>
</div>


<style>
.top{
    padding-right: 20px;
}
.content{
    padding: 30px;
}
.sideBox{
    padding: 30px;

}
.bg-cart {
    background-color: orange;
    color: #fff
}

.bg-cart:hover {
    color: #fff
}
#product_quantity {
    width: 40px;
}
.c-error { 
  border-radius: 0 !important;
  position: relative; 
  display: inline-block !important;
  color: #c51244 !important;
}





</style>

app/views/cart_items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cart_item %>

<div>
  <%= link_to "Edit this cart item", edit_cart_item_path(@cart_item) %> |
  <%= link_to "Back to cart items", cart_items_path %>

  <%= button_to "Destroy this cart item", @cart_item, method: :delete %>
</div>