config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :products, only: [:index]
      post '/api-keys', to: 'api_keys#create'
      delete '/api-keys', to: 'api_keys#destroy'
      get '/api-keys', to: 'api_keys#index'
      # put '/user_edit',to: 'api_keys#user_edit'
      put '/user_edit/:id',to: 'tests#user_edit'

    end
  end

  resources :payment_notifications
  resources :order2s
  get '/express', to: 'order2s#express'
  
  # get '/user_feedbacks/new', to: "user_feedbacks#new"
  # post '/user_feedbacks', to: "user_feedbacks#create"
  resources :user_feed_backs
  post '/rate' => 'rater#create', :as => 'rate'
  # get 'emails/unsubscribe'
  
 get '/orders', to: 'orders#index'
 post '/orders/submit', to: "orders#submit"


  resources :projects do
    resources :tasks
  end

  get 'checkout', to: "checkout#index"

  resources :cart_items
  resources :carts
  resources :posts
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    namespace :admin do
      # resources :cars
      resources :users
      resources :categories
      resources :products
      root to: "users#index"
      
    end
    resources :products

    match "users/unsubscribe/:unsubscribe_hash" => "emails#unsubscribe", as: "unsubscribe", via: :all



    get "subcategories" , to: "products#subcategories"

   resources :cars

  #  devise_for :users, path: '', path_names: {
  #   sign_in: 'login',
  #   sign_out: 'logout',
  #   registration: 'signup'
  # },
  # controllers: {
  #   sessions: 'sessions',
  #   registrations: 'registrations'
  # }


  devise_for :users, :controllers => {:sessions => 'sessions', registrations: 'registrations'}
  root 'home#index'
  post "address/new" , to: "checkout#create"
  post "place_order" , to: "checkout#place_order"
  get "checkout/place_order" , to: "checkout#place_order_new"
  post "cart_items/quantity_update" , to: "cart_items#quantity_update"

  # delete "address/destroy/:id" , to: "checkout#destroy"
  delete "address/destroy/:id" , to: "checkout#destroy", as: "address_destroy"
  # resources :addresses
  # scope module: 'admin', path: 'fu' do
  #   resources :users
  # end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_categories
  has_many :categories, through: :product_categories
  has_many :cart_items, dependent: :destroy
  has_rich_text :description
  mount_uploader :image, ImageUploader
  has_many :user_feed_backs, dependent: :destroy

  validates :title, presence: true, length: { minimum: 2,  maximum: 100}
  # validates :description, presence: true, length: { minimum: 3, maximum: 400}
  validates :price, presence: true
  validates :image, presence: true
 


  FINISH = %w{ Black White Navy Blue Red Clear Satin Yellow Seafoam }
  CONDITION = %w{ New Excellent Mint Used Fair Poor }

end

app/controllers/admin/products_controller.rb
module Admin
    class ProductsController < Admin::ApplicationController
      # Overwrite any of the RESTful controller actions to implement custom behavior
      # For example, you may want to send an email after a foo is updated.
      #
      # def update
      #   super
      #   send_foo_updated_email(requested_resource)
      # end
      def index
        @products = Product.all
      end


      def new
        @product = Product.new
      end
     
      def edit
        @product = Product.find(params[:id])
      end

      # POST /instruments or /instruments.json
  def create
    @product =  Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_product_path(@product), notice: "product was successfully created." }
        format.json { render :show, status: :created, location: @instrument }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params())

      flash[:notice] = "product was updated successfully."
      redirect_to admin_product_path(@product)
    else
      respond_to do |format|
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  private

  def product_params
    params.require(:product).permit(:brand, :model, :description, :condition, :finish, :price, :title,:image, :quantity, category_ids: [])
    # params.require(:product).permit(:title, :description, :dat_created, :picture, category_ids: [])
  end
      # Override this method to specify custom lookup behavior.
      # This will be used to set the resource for the `show`, `edit`, and `update`
      # actions.
      #
      # def find_resource(param)
      #   Foo.find_by!(slug: param)
      # end
  
      # The result of this lookup will be available as `requested_resource`
  
      # Override this if you have certain roles that require a subset
      # this will be used to set the records shown on the `index` action.
      #
      # def scoped_resource
      #   if current_user.super_admin?
      #     resource_class
      #   else
      #     resource_class.with_less_stuff
      #   end
      # end
  
      # Override `resource_params` if you want to transform the submitted
      # data before it's persisted. For example, the following would turn all
      # empty values into nil values. It uses other APIs such as `resource_class`
      # and `dashboard`:
      #
      # def resource_params
      #   params.require(resource_class.model_name.param_key).
      #     permit(dashboard.permitted_attributes).
      #     transform_values { |value| value == "" ? nil : value }
      # end
  
      # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
      # for more information
    end
  end
  

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:index]
  #  skip_before_action :verify_authenticity_token, only: [ :index]
  # before_action :authenticate_user!, only: [:index]
 
  respond_to :json
  before_action :process_token

  # before_action :authenticate_user!
  # def index
  #   render json: current_user, status: :ok
  # end


  def index
     @products = Product.all
    #  render json: @products
     render json: @products, status: :ok
  end
  
 
end

app/controllers/products_controller.rb
    class ProductsController < ApplicationController
      before_action :set_cart
      def index
        
       unless params[:category_id].blank?
        @category = Category.find(params[:category_id])
        @products =  @category.products
        else
        @products = Product.all
        end
      end

      def subcategories
        @category = Category.find(params[:category_id])
        @sub_categories = @category.subcategories
        if  @sub_categories
          render partial: "shared/data"
        end
      end



      def new
        @product = Product.new
      end
     
      def edit
        @product = Product.find(params[:id])
      end
      def show
        @cart_item = CartItem.new
        @product = Product.find(params[:id])
        @user_feed_back_data =  UserFeedBack.where(product_id: @product.id)
        @user_feed_backs =   UserFeedBack.find_by(product_id: @product.id, user_id: current_user.id)
        if  @user_feed_backs.blank?
        #   @user_feed_backs = UserFeedBack.find_by(product_id: @product.id, user_id: current_user.id)
        # else
          @user_feed_backs = UserFeedBack.new
        end
      end

      # POST /instruments or /instruments.json
  def create
    @product =  Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_product_path(@product), notice: "product was successfully created." }
        format.json { render :show, status: :created, location: @instrument }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params())

      flash[:notice] = "product was updated successfully."
      redirect_to admin_product_path(@product)
    else
      respond_to do |format|
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  private

  def product_params
    params.require(:product).permit(:brand, :model, :description, :condition, :finish, :price, :title, category_ids: [])
    # params.require(:product).permit(:title, :description, :dat_created, :picture, category_ids: [])
  end
      
    end
  

app/views/admin/products/_form.html.erb
<%= form_with(model: @product, url:  (@product.id.blank? ? admin_products_path  : admin_product_path(@product)),class: " p-3 mb-3 rounded", local: true) do |f| %>
  <%= render 'admin/shared/errors' %>
<%#  form_with(model: @product, url:  admin_products_path,class: "shadow p-3 mb-3 bg-success rounded", local: true) do |f| %>

    <div class="field-unit field-unit--string field-unit--optional">
      <div class="field-unit__label">
      <%= f.label :title, class: "col-2 col-form-label text-light" %>
      </div>
      <div class="field-unit__field">
      <%= f.text_field :title,class: "form-control shadow rounded", placeholder: "Enter title" %>
      </div>
    </div>


    <div class="field-unit field-unit--string field-unit--optional">
      <div class="field-unit__label">
      <%= f.label :price, class: "col-2 col-form-label text-light" %>
      </div>
      <div class="field-unit__field">
      <%= f.number_field :price,class: "form-control shadow rounded" %>
      </div>
    </div>

    <div class="field-unit field-unit--string field-unit--optional">
      <div class="field-unit__label">
      <%= f.label :quantity, class: "col-2 col-form-label text-light" %>
      </div>
      <div class="field-unit__field">
      <%= f.number_field :quantity,class: "form-control shadow rounded" %>
      </div>
    </div>


  <div class="field-unit field-unit--string field-unit--optional">
  <div class="field-unit__label">
  <%= f.label :model, class: "col-2 col-form-label text-light" %>
  </div>
  <div class="field-unit__field">
  <%= f.text_field :model,class: "form-control shadow rounded", placeholder: "Enter model" %>
  </div>
</div>

<div class="field-unit field-unit--string field-unit--optional">
  <div class="field-unit__label">
  <%= f.label :description,class: "col-2 col-form-label text-light" %>
  </div>
  <div class="field-unit__field">
  <%= f.rich_text_area :description, class: "input h-32 border border-grey-light resize-none", placeholder: "Enter description" %>
  <% #  f.rich_text_area :description, input: "product_description", id: "product_description_trix" %>
  </div>
</div>
<div class="field-unit field-unit--string field-unit--optional">
<div class="field-unit__label">

<%= f.label :category, class: "col-2 col-form-label text-light"  %>
</div>
<div class="field-unit__field">
<%= f.collection_select :category_ids, Category.order(:name), :id, :name, 
{prompt: "Please Select category"}, {multiple: true, size:4,class: "form-select shadow rounded"} %>
</div> 
</div>  

<div class="field-unit field-unit--string field-unit--optional">
  <div class="field-unit__label">
  <%= f.label :brand,class: "col-2 col-form-label text-light" %>
  </div>
  <div class="field-unit__field">
  <%= f.text_field :brand,class: "form-control shadow rounded", placeholder: "Enter brand" %>

  </div>
</div>

<div class="field-unit field-unit--string field-unit--optional">
  <div class="field-unit__label">
  <%= f.label :finish,class: "col-2 col-form-label text-light" %>
  </div>
  <div class="field-unit__field">
  <% # f.select :finish, options_for_select(Product::FINISH), class: "form-control shadow rounded"%>
  <%= f.select :finish, options_for_select(Product::FINISH) %>

  </div>
</div>


<div class="field-unit field-unit--string field-unit--optional">
  <div class="field-unit__label">
  <%= f.label :condition,class: "col-2 col-form-label text-light" %>
  </div>
  <div class="field-unit__field">
  <%= f.select :condition, options_for_select(Product::CONDITION) %>

  </div>
</div>


<div class="field-unit field-unit--string field-unit--optional">
  <div class="field-unit__label">
  <%= f.label :image,class: "col-2 col-form-label text-light" %>
  </div>
  <div class="field-unit__field">
  <%= f.file_field :image,class: "form-control shadow rounded product-image", placeholder: "Enter category name" %>
 
  </div>
</div>
  <div class="field-unit field-unit--string field-unit--optional image-preview">  
  <output id="list"></output>
  </div>
<% if @product.image.url %>
<div class="feature-image image-preview" id="edit-img">
<%= link_to image_tag(@product.image.url, size: "200x200" ) %>
</div>
<%end%>

<div class="form-actions">
      <%= f.submit  class: "btn btn-outline-light" %> 
  </div>
<% end %>

<style>

.image-preview{
padding-left: 18%;

}
</style>

app/views/admin/products/_product.html.erb
  
   
        <tr class="js-table-row" tabindex="0" role="link" data-url="/admin/products/5">
            <td class="cell-data cell-data--number">
            <%= product.id %>
            </td>
            <td class="cell-data cell-data--string">
            <%= product.brand %>
            </td>
            <td class="cell-data cell-data--string">
            <%= product.model %>
            </td>
            <td class="cell-data cell-data--string">
            <% # product.description.to_plain_text.truncate(70)  %>
            <%= product.description.to_plain_text  %>

            </td>
            <td class="cell-data cell-data--string">
            <%= product.finish %>
            </td>
            <td class="cell-data cell-data--string">
            <%= product.title %>
            </td>

            <td class="cell-data cell-data--string">
            <i> <% if product.categories.any? %>
            <div class="mt-2"><%= render product.categories %></div>
            <% end %></i>
            </td>
            <td class="cell-data cell-data--number">
                <a href="/admin/products/5" tabindex="-1" class="action-show">
                <%=  number_to_currency(product.price) %>
                 
                </a>
            </td>
            <td><%= link_to "Edit" , edit_admin_product_path(product) , class: "button action-edit text-color-yellow" %></td>
            <td> <%= button_to "delete", admin_product_path(product), method: :delete , form: {data: {turbo_confirm: 'Are you sure?'}}, class: "text-color-red" %> </td>
  
        </tr>

app/views/admin/products/edit.html.erb
<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
  Edit Product 
  </h1>

  <div>
  <%= link_to 'Back', admin_categories_path , class: "button btn btn-outline-light"%>
  </div>
</header>


  <section class="main-content__body">
    <%= render 'form', product: @product %>
  </section>

app/views/admin/products/index.html.erb
<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title" id="page-title">
       Products
  </h1>

    
  <div>
  <%= link_to "New Product" ,new_admin_product_path ,class: "button"%>
  </div>
</header>




<section class="main-content__body main-content__body--flush">
  
<table aria-labelledby="page-title">
  <thead>
    <tr>
        <th class="cell-label
        cell-label--number
        cell-label--false
        cell-label--product_id" scope="col" role="columnheader" aria-sort="none">
        <a href="/admin/products?product%5Bdirection%5D=asc&amp;product%5Border%5D=id">
        Id
</a>        </th>
        <th class="cell-label
        cell-label--string
        cell-label--false
        cell-label--product_brand" scope="col" role="columnheader" aria-sort="none">
        <a href="/admin/products?product%5Bdirection%5D=asc&amp;product%5Border%5D=brand">
        Brand
</a>        </th>
        <th class="cell-label
        cell-label--string
        cell-label--false
        cell-label--product_model" scope="col" role="columnheader" aria-sort="none">
        <a href="/admin/products?product%5Bdirection%5D=asc&amp;product%5Border%5D=model">
        Model
</a>        </th>
        <th class="cell-label
        cell-label--string
        cell-label--false
        cell-label--product_description" scope="col" role="columnheader" aria-sort="none">
        <a href="/admin/products?product%5Bdirection%5D=asc&amp;product%5Border%5D=description">
        Description
</a>        </th>
        <th class="cell-label
        cell-label--string
        cell-label--false
        cell-label--product_finish" scope="col" role="columnheader" aria-sort="none">
        <a href="/admin/products?product%5Bdirection%5D=asc&amp;product%5Border%5D=finish">
        Finish
</a>        </th>
        <th class="cell-label
        cell-label--string
        cell-label--false
        cell-label--product_title" scope="col" role="columnheader" aria-sort="none">
        <a href="/admin/products?product%5Bdirection%5D=asc&amp;product%5Border%5D=title">
        Title
</a>        </th>

<th class="cell-label
cell-label--string
cell-label--false
cell-label--product_title" scope="col" role="columnheader" aria-sort="none">
<a href="/admin/products?product%5Bdirection%5D=asc&amp;product%5Border%5D=title">
Categories
</a>        </th>



        <th class="cell-label
        cell-label--number
        cell-label--false
        cell-label--product_price" scope="col" role="columnheader" aria-sort="none">
        <a href="/admin/products?product%5Bdirection%5D=asc&amp;product%5Border%5D=price">
        Price
</a>        </th>
        <th scope="col"></th>
  <th scope="col"></th>

    </tr>
  </thead>
  <tbody>
  <% @products.each do |product| %>
    <%= render product %>
  <% end %>
  </tbody>
  </table>
  </section>

app/views/admin/products/new.html.erb
<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
  New Product
  </h1>

  <div>
  <%= link_to 'Back', admin_categories_path , class: "button btn btn-outline-light"%>
  </div>
</header>


  <section class="main-content__body">
    <%= render 'form', product: @product %>
  </section>